import { ActionLink, Filters, Page, Panel, Status, usePermissions } from '@/components/erp/page';
import { Pagination, Table } from '@/components/erp/table';
import { date, money } from '@/lib/format';
import { due } from '@/lib/pricing';
import { PageData, PurchaseOrder, Receipt } from '@/types/erp';
import { Link } from '@inertiajs/react';
export default function Purchasing({ receipts, orders, filters }: { receipts: PageData<Receipt>; orders: PageData<PurchaseOrder>; filters: { q: string; from: string; to: string } }) {
    const can = usePermissions();
    return <Page title="Purchasing" description="Order from suppliers, receive goods, and settle supplier invoices." actions={can('inventory.receive') && <ActionLink href="/purchasing/create">Order / receive goods</ActionLink>}><Panel title="Open purchase orders" description="Receive an order in full or in multiple deliveries."><Table rows={orders.data} columns={[{ label: 'Order', render: o => <Link className="text-primary font-medium" href={`/purchasing/create?order=${o.id}`}>{o.number}</Link> }, { label: 'Supplier', render: o => o.supplier.name }, { label: 'Destination', render: o => o.location.name }, { label: 'Expected', render: o => date(o.expected_on) }, { label: 'Status', render: o => <Status tone={o.status === 'partial' ? 'warning' : 'neutral'}>{o.status}</Status> }, { label: 'Value', render: o => money(o.total_amount) }]} /><Pagination page={orders} /></Panel><Filters path="/purchasing" initial={filters} /><Panel title="Received goods / supplier invoices"><Table rows={receipts.data} columns={[{ label: 'Receipt', render: r => <Link className="text-primary font-medium" href={`/purchasing/receipts/${r.id}`}>{r.number ?? r.id.slice(0,8)}<p className="text-muted-foreground text-xs">{r.supplier_reference}</p></Link> }, { label: 'Supplier', render: r => r.supplier.name }, { label: 'Received', render: r => date(r.posted_at) }, { label: 'Location', render: r => r.location.name }, { label: 'Total', render: r => money(r.total_amount) }, { label: 'Balance', render: r => <Status tone={Number(due(r.total_amount,r.returned_amount,r.paid_amount)) > 0 ? 'warning' : 'good'}>{money(due(r.total_amount,r.returned_amount,r.paid_amount))}</Status> }]} /><Pagination page={receipts} /></Panel></Page>;
}
