import { Field } from '@/components/erp/field';
import { Feedback, Metric, Page, Panel, Submit, usePermissions } from '@/components/erp/page';
import { ErpSelect } from '@/components/erp/select';
import { Table } from '@/components/erp/table';
import { useTransaction } from '@/hooks/use-transaction';
import { date, money, quantity } from '@/lib/format';
import { due, scaled } from '@/lib/pricing';
import { Receipt } from '@/types/erp';
import { router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

export default function ReceiptShow({ receipt }: { receipt: Receipt }) {
    const can = usePermissions(); const balance = due(receipt.total_amount, receipt.returned_amount, receipt.paid_amount);
    return <Page title={receipt.number ?? 'Goods receipt'} description={`${receipt.supplier.name} · ${receipt.location.name} · ${date(receipt.posted_at, true)}${receipt.supplier_reference ? ` · Supplier reference ${receipt.supplier_reference}` : ''}`}><div className="grid gap-4 sm:grid-cols-3"><Metric label="Received value" value={money(receipt.total_amount)} /><Metric label="Supplier payments" value={money(receipt.paid_amount)} /><Metric label={Number(balance) < 0 ? 'Supplier credit held' : 'Supplier balance due'} value={money(Number(balance) < 0 ? -Number(balance) : balance)} detail={`${money(receipt.returned_amount)} in returns`} /></div><Panel title="Received items"><Table rows={receipt.lines} columns={[{ label: 'Product', render: l => <div>{l.product.name}<p className="text-muted-foreground text-xs">{l.product.sku}</p></div> }, { label: 'Batch / expiry', render: l => <div>{l.batch?.batch_no ?? '—'}<p className="text-muted-foreground text-xs">{date(l.batch?.expiry_date)}</p></div> }, { label: 'Received', render: l => `${quantity(l.quantity_received)} ${l.product.stock_unit}` }, { label: 'Returned', render: l => quantity(l.returned_quantity) }, { label: 'Unit cost', render: l => money(l.unit_cost) }, { label: 'Total', render: l => money(l.line_total) }]} /></Panel><div className="grid gap-6 lg:grid-cols-2"><Panel title="Supplier payment history"><Table rows={receipt.payments} columns={[{ label: 'Paid', render: p => date(p.paid_at) }, { label: 'Method', render: p => p.method }, { label: 'Reference', render: p => p.reference ?? 'Cash' }, { label: 'Amount', render: p => money(p.amount) }]} /></Panel><Panel title="Purchase returns"><Table rows={receipt.returns} columns={[{ label: 'Reference', render: r => r.number }, { label: 'Reason', render: r => r.reason }, { label: 'Credit', render: r => money(r.total_amount) }]} /></Panel></div><div className="grid gap-6 lg:grid-cols-2">{can('finance.manage') && Number(balance) > 0 && <PaymentForm receipt={receipt} balance={balance} />}{can('purchasing.manage') && receipt.lines.some(l => Number(l.quantity_received) > Number(l.returned_quantity)) && <ReturnForm receipt={receipt} />}</div></Page>;
}
function PaymentForm({ receipt, balance }: { receipt: Receipt; balance: string }) {
    const tx = useTransaction(`supplier-payment:${receipt.id}`); const [amount,setAmount] = useState(balance); const [method,setMethod] = useState('bank'); const [reference,setReference] = useState('');
    async function submit(e: FormEvent) { e.preventDefault(); if (await tx.send(`/api/goods-receipts/${receipt.id}/payments`, { amount, method, reference: reference || null })) router.reload(); }
    return <Panel title="Pay supplier"><form onSubmit={submit} className="space-y-4 p-5"><fieldset disabled={tx.busy || tx.uncertain} className="grid gap-4"><Field label="Amount (BDT)"><input className="erp-input" type="number" min=".01" step=".01" max={balance} required value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label="Payment method"><ErpSelect value={method} onChange={setMethod} options={['bank','cash','card','mobile'].map(m => ({ value: m, label: m[0].toUpperCase() + m.slice(1) }))} /></Field><Field label="Transaction reference"><input className="erp-input" required={method !== 'cash'} value={reference} onChange={e => setReference(e.target.value)} /></Field></fieldset><Feedback {...tx} /><Submit {...tx}>Record supplier payment</Submit></form></Panel>;
}
function ReturnForm({ receipt }: { receipt: Receipt }) {
    const tx = useTransaction(`purchase-return:${receipt.id}`); const [quantities,setQuantities] = useState<Record<string,string>>({}); const [reason,setReason] = useState('');
    async function submit(e: FormEvent) { e.preventDefault(); if (await tx.send(`/api/goods-receipts/${receipt.id}/returns`, { reason, lines: Object.entries(quantities).filter(([,q]) => scaled(q,3) > 0n).map(([goods_receipt_line_id, q]) => ({ goods_receipt_line_id, quantity: q })) })) { setQuantities({}); router.reload(); } }
    return <Panel title="Return goods to supplier" description="Stock must be available at the original receiving location. Returns reduce the invoice balance; excess paid amounts remain a supplier credit."><form onSubmit={submit} className="space-y-4 p-5"><fieldset disabled={tx.busy || tx.uncertain} className="space-y-4">{receipt.lines.filter(l => Number(l.quantity_received) > Number(l.returned_quantity)).map(l => <Field key={l.id} label={`${l.product.name} · ${quantity(Number(l.quantity_received)-Number(l.returned_quantity))} returnable`}><input className="erp-input" type="number" min="0" step=".001" value={quantities[l.id] ?? '0'} onChange={e => setQuantities({ ...quantities, [l.id]: e.target.value })} /></Field>)}<Field label="Reason"><textarea className="erp-input" required minLength={3} value={reason} onChange={e => setReason(e.target.value)} /></Field></fieldset><Feedback {...tx} /><Submit {...tx}>Post purchase return</Submit></form></Panel>;
}
