import { Field } from '@/components/erp/field';
import { Feedback, Metric, Page, Panel, Status, Submit, usePermissions } from '@/components/erp/page';
import { ErpSelect } from '@/components/erp/select';
import { Table } from '@/components/erp/table';
import { Button } from '@/components/ui/button';
import { useTransaction } from '@/hooks/use-transaction';
import { date, money, quantity } from '@/lib/format';
import { due, scaled } from '@/lib/pricing';
import { SharedData } from '@/types';
import { Location, Sale, Shift } from '@/types/erp';
import { Link, router, usePage } from '@inertiajs/react';
import { Printer } from 'lucide-react';
import { FormEvent, useState } from 'react';

export default function SaleShow({ sale, locations, shift }: { sale: Sale; locations: Location[]; shift: Shift | null }) {
    const can = usePermissions(); const { erp } = usePage<SharedData>().props;
    const outstanding = due(sale.grand_total, sale.returned_amount, sale.paid_amount, sale.refunded_amount);
    return <Page title={sale.number} description={`${date(sale.posted_at, true)} · ${sale.cashier?.name} · ${sale.location?.name}`} actions={<><Button variant="outline" onClick={() => window.print()}><Printer className="size-4" />Print receipt</Button>{can('sales.create') && <Button asChild><Link href="/pos">Next sale</Link></Button>}</>}>
        <div className="no-print grid gap-4 sm:grid-cols-3"><Metric label="Sale total" value={money(sale.grand_total)} /><Metric label="Returned value" value={money(sale.returned_amount)} /><Metric label="Outstanding balance" value={money(outstanding)} detail={sale.customer?.name ?? 'Walk-in customer'} /></div>
        <Panel><div className="print-receipt p-5"><div className="print-only mb-5 text-center"><h1 className="text-xl font-bold">{erp?.name ?? 'FreshMart'}</h1>{erp?.address && <p>{erp.address}</p>}{erp?.phone && <p>{erp.phone}</p>}<p className="mt-2 font-semibold">{sale.number}</p><p>{date(sale.posted_at, true)}</p><p>Cashier: {sale.cashier?.name}</p><p>Customer: {sale.customer?.name ?? 'Walk-in'}</p></div><Table rows={sale.lines} columns={[{ label: 'Item', render: l => <div className="font-medium">{l.product_name}<p className="text-muted-foreground text-xs">{l.sku}</p></div> }, { label: 'Qty', render: l => `${quantity(l.quantity)} ${l.stock_unit}` }, { label: 'Unit price', render: l => money(l.unit_price) }, { label: 'Discount', render: l => money(l.discount_amount) }, { label: 'Tax', render: l => money(l.tax_amount) }, { label: 'Total', className: 'text-right font-medium tabular-nums', render: l => money(l.line_total) }]} /><dl className="ml-auto mt-5 max-w-sm space-y-2 text-sm">{[['Subtotal after discounts', sale.subtotal], ['Tax', sale.tax_total], ['Total', sale.grand_total], ['Tendered at checkout', sale.tendered_amount], ['Change given', sale.change_amount], ['Total paid', sale.paid_amount], ['Total refunded', sale.refunded_amount], ['Amount due', outstanding]].map(([label, value]) => <div className={`flex justify-between gap-6 ${label === 'Total' ? 'border-t pt-3 text-lg font-semibold' : ''}`} key={label}><dt>{label}</dt><dd className="tabular-nums">{money(value)}</dd></div>)}</dl>{sale.notes && <p className="text-muted-foreground mt-4 text-sm">Note: {sale.notes}</p>}<p className="print-only mt-6 text-center">Thank you for shopping with us. Keep this receipt for returns.</p></div></Panel>
        <div className="no-print grid gap-6 lg:grid-cols-2"><Panel title="Payment history"><Table rows={sale.payments} columns={[{ label: 'Date', render: p => date(p.paid_at, true) }, { label: 'Method / reference', render: p => <div className="capitalize">{p.method}<p className="text-muted-foreground text-xs">{p.reference ?? 'Cash'}</p></div> }, { label: 'Type', render: p => <Status tone={p.kind === 'refund' ? 'warning' : 'good'}>{p.kind}</Status> }, { label: 'Amount', render: p => money(p.amount) }]} /></Panel><Panel title="Returns and credit notes"><Table rows={sale.returns} columns={[{ label: 'Reference', render: r => r.number }, { label: 'Reason', render: r => r.reason }, { label: 'Credit', render: r => money(r.total_amount) }, { label: 'Refund', render: r => money(r.refund_amount) }]} /></Panel></div>
        <div className="no-print grid gap-6 xl:grid-cols-2">{can('finance.manage') && Number(outstanding) > 0 && <CollectPayment sale={sale} shift={shift} outstanding={outstanding} />}{can('sales.return') && sale.lines.some(l => Number(l.returned_quantity) < Number(l.quantity)) && <ReturnForm sale={sale} locations={locations} shift={shift} />}</div>
    </Page>;
}
function CollectPayment({ sale, shift, outstanding }: { sale: Sale; shift: Shift | null; outstanding: string }) {
    const tx = useTransaction(`customer-payment:${sale.id}`); const [amount, setAmount] = useState(outstanding); const [method, setMethod] = useState(shift ? 'cash' : 'bank'); const [reference, setReference] = useState('');
    async function submit(e: FormEvent) { e.preventDefault(); if (await tx.send(`/api/sales/${sale.id}/payments`, { amount, method, reference: reference || null, shift_id: shift?.id ?? null })) router.reload(); }
    return <Panel title="Collect outstanding payment" description="Cash collections are recorded against your open till."><form onSubmit={submit} className="space-y-4 p-5"><fieldset disabled={tx.busy || tx.uncertain} className="grid gap-4 sm:grid-cols-2"><Field label="Amount (BDT)"><input className="erp-input" type="number" step="0.01" min="0.01" max={outstanding} value={amount} onChange={e => setAmount(e.target.value)} required /></Field><Field label="Payment method"><ErpSelect value={method} onChange={setMethod} options={['cash','bank','card','mobile'].map(m => ({ value: m, label: m[0].toUpperCase() + m.slice(1) }))} /></Field><Field label="Transaction reference"><input className="erp-input" required={method !== 'cash'} value={reference} onChange={e => setReference(e.target.value)} /></Field></fieldset><Feedback {...tx} /><Submit {...tx}>Record payment</Submit></form></Panel>;
}
function ReturnForm({ sale, locations, shift }: { sale: Sale; locations: Location[]; shift: Shift | null }) {
    const tx = useTransaction(`sales-return:${sale.id}`); const [quantities, setQuantities] = useState<Record<string,string>>({}); const [reason, setReason] = useState(''); const [disposition, setDisposition] = useState('restock'); const [location, setLocation] = useState(sale.location_id); const [method, setMethod] = useState(shift ? 'cash' : 'bank'); const [reference, setReference] = useState('');
    async function submit(e: FormEvent) { e.preventDefault(); const result = await tx.send(`/api/sales/${sale.id}/returns`, { lines: Object.entries(quantities).filter(([,q]) => scaled(q,3) > 0n).map(([sale_line_id, q]) => ({ sale_line_id, quantity: q })), reason, disposition, location_id: location, refund_method: method, reference: reference || null, shift_id: shift?.id ?? null }); if (result) { setQuantities({}); setReason(''); router.reload(); } }
    return <Panel title="Return items" description="Original prices and discounts determine the credit. Unpaid balances are settled before money is refunded."><form onSubmit={submit} className="space-y-4 p-5"><fieldset disabled={tx.busy || tx.uncertain} className="space-y-4">{sale.lines.filter(l => Number(l.quantity) > Number(l.returned_quantity)).map(l => <Field key={l.id} label={`${l.product_name} · ${quantity(Number(l.quantity) - Number(l.returned_quantity))} available to return`}><input className="erp-input" type="number" min="0" step="0.001" max={Number(l.quantity) - Number(l.returned_quantity)} value={quantities[l.id] ?? '0'} onChange={e => setQuantities({ ...quantities, [l.id]: e.target.value })} /></Field>)}<div className="grid gap-4 sm:grid-cols-2"><Field label="Stock disposition"><ErpSelect value={disposition} onChange={v => { setDisposition(v); setLocation(v === 'restock' ? sale.location_id : locations.find(l => l.type === 'quarantine')?.id ?? ''); }} options={[{ value: 'restock', label: 'Restock saleable goods' }, { value: 'quarantine', label: 'Quarantine damaged / expired goods' }]} /></Field><Field label="Receiving location"><ErpSelect value={location} onChange={setLocation} placeholder="Choose location" options={locations.filter(l => disposition === 'quarantine' ? l.type === 'quarantine' : l.id === sale.location_id).map(l => ({ value: l.id, label: l.name }))} /></Field><Field label="Refund method"><ErpSelect value={method} onChange={setMethod} options={['cash','bank','card','mobile'].map(m => ({ value: m, label: m[0].toUpperCase() + m.slice(1) }))} /></Field><Field label="Refund transaction reference"><input className="erp-input" value={reference} onChange={e => setReference(e.target.value)} /></Field></div><Field label="Return reason"><textarea className="erp-input" minLength={3} required value={reason} onChange={e => setReason(e.target.value)} /></Field></fieldset><Feedback {...tx} /><Submit {...tx}>Post return and refund</Submit></form></Panel>;
}
