import { ActionLink, Empty, Metric, Page, Panel, Status, usePermissions } from '@/components/erp/page';
import { SalesTrendChart } from '@/components/erp/sales-trend-chart';
import { Table } from '@/components/erp/table';
import { date, money, quantity } from '@/lib/format';
import { Alerts, Sale, Shift, Summary } from '@/types/erp';
import { Link } from '@inertiajs/react';
import { ArrowUpRight, Boxes, Clock3, PackageCheck, Receipt, TrendingUp, Wallet } from 'lucide-react';

export default function Overview({ summary, trend, alerts, recentSales, shift, businessDate }: { summary: Summary | null; trend: { day: string; net_sales: string; profit: string }[]; alerts: Alerts | null; recentSales: Sale[]; shift: Shift | null; businessDate: string }) {
    const can = usePermissions();
    const needsAttention = !!alerts && (alerts.low_count > 0 || alerts.out_count > 0);
    return <Page title="Store overview" description={`${date(businessDate)} · Your daily view of trading, inventory and outstanding accounts.`} actions={can('sales.create') && <ActionLink href="/pos">Open point of sale</ActionLink>}>
        {summary ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Today's net sales" value={money(summary.net_sales)} detail="After returns · excludes tax" tone="success" icon={Wallet} /><Metric label="Estimated gross profit" value={money(summary.gross_profit)} detail={summary.margin ? `${summary.margin}% of net sales` : 'Sales less inventory cost'} tone="info" icon={TrendingUp} /><Metric label="Transactions today" value={summary.transactions} detail={`${money(summary.average_order)} average sale, including tax`} tone="analytics" icon={Receipt} /><Metric label="Inventory valuation" value={money(summary.inventory_value)} detail={needsAttention ? `${alerts!.low_count + alerts!.out_count} products need attention` : 'Current stock at average cost'} tone={needsAttention ? 'warning' : 'neutral'} icon={Boxes} /></div><div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Panel title="Sales over the last 30 days" description="Net sales excluding tax; returns are recorded on the day they are posted." action={<Link className="text-primary flex items-center gap-1 text-xs font-medium" href="/reports">View reports<ArrowUpRight className="size-3" /></Link>}><SalesTrendChart trend={trend} /></Panel><Panel title="Accounts & cash" description="Balances are current; activity totals are for today."><dl className="divide-y px-5">{[['Receivables', summary.receivables], ['Supplier payables', summary.payables], ['Supplier credits', summary.supplier_credits], ['Expenses today', summary.expenses], ['Net operating cash flow today', summary.cash_flow]].map(([label, value]) => <div key={label} className="flex justify-between gap-3 py-3.5 text-sm"><dt className="text-muted-foreground">{label}</dt><dd className="font-medium tabular-nums">{money(value)}</dd></div>)}</dl></Panel></div></> : <Panel><div className="flex items-center gap-4 p-6"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-400"><PackageCheck /></div><div><h2 className="font-semibold">Ready for your next task</h2><p className="text-muted-foreground mt-1 text-sm">{shift ? `Your shift at ${shift.counter} is open.` : 'Use the navigation to access your assigned store workflows.'}</p></div></div></Panel>}
        <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><Panel title="Recent sales" action={can('sales.create') || can('sales.view-all') ? <Link href="/sales" className="text-primary text-xs font-medium">All sales →</Link> : undefined}><Table rows={recentSales} columns={[{ label: 'Receipt', render: s => <Link className="text-primary font-medium" href={`/sales/${s.id}`}>{s.number}</Link> }, { label: 'Customer', render: s => <div>{s.customer?.name ?? 'Walk-in customer'}<p className="text-muted-foreground text-xs">{s.cashier?.name}</p></div> }, { label: 'Date', render: s => date(s.posted_at, true) }, { label: 'Total', className: 'text-right tabular-nums', render: s => money(s.grand_total) }]} /></Panel>{alerts && <Panel title="Stock needs attention" description={`${alerts.low_count} low-stock products · ${alerts.out_count} out of stock`} action={<Link href="/inventory?status=low" className="text-primary text-xs font-medium">Review →</Link>}>{alerts.low_stock.length ? <div className="divide-y px-5">{alerts.low_stock.map(p => <Link href={`/inventory/stock/${p.id}`} key={p.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{p.name}</p><p className="text-muted-foreground text-xs">{p.sku}</p></div><Status tone={Number(p.available) === 0 ? 'danger' : 'warning'}>{quantity(p.available)} {p.stock_unit}</Status></Link>)}</div> : <Empty title="Stock levels look healthy" description="Products below their reorder levels appear here." />}</Panel>}</div>
        {alerts && alerts.expiring.length > 0 && <Panel title="Use or review soon" description="Batches expiring within 30 days, ordered by expiry date."><div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4">{alerts.expiring.map(p => <Link href={`/inventory/stock/${p.id}`} key={`${p.id}-${p.batch_no}-${p.location}`} className="rounded-lg border bg-amber-50/40 p-4 dark:bg-amber-950/10"><p className="text-sm font-semibold">{p.name}</p><p className="text-muted-foreground mt-1 text-xs">{p.batch_no} · {p.location}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-amber-800 dark:text-amber-300"><Clock3 className="size-3.5" />{date(p.expiry_date)} · {quantity(p.quantity_on_hand)} remaining</p></Link>)}</div></Panel>}
    </Page>;
}
