import { ActionLink, Filters, Metric, Page, Panel, Status, usePermissions } from '@/components/erp/page';
import { Pagination, Table } from '@/components/erp/table';
import { money, quantity } from '@/lib/format';
import { Alerts, PageData, StockRow } from '@/types/erp';
import { Link } from '@inertiajs/react';

export default function Inventory({ products, alerts, filters }: { products: PageData<StockRow>; alerts: Alerts; filters: { q: string; status: string } }) {
    const can = usePermissions();
    return <Page title="Stock overview" description="Saleable inventory across the store. Expired and quarantined stock is excluded from available quantities." actions={can('inventory.receive') && <ActionLink href="/purchasing/create">Receive goods</ActionLink>}><div className="grid gap-4 sm:grid-cols-3"><Metric label="Low-stock products" value={alerts.low_count} detail="At or below the reorder level" /><Metric label="Out of stock" value={alerts.out_count} detail="No saleable inventory" /><Metric label="Expiry review" value={alerts.expiring.length ? `${alerts.expiring.length} priority batches` : 'No upcoming expiry'} detail="Nearest expiries within 30 days" /></div><div className="flex flex-wrap items-end justify-between gap-3"><Filters path="/inventory" initial={filters} dates={false} /><div className="flex gap-3 text-sm"><Link className="text-primary" href="/inventory">All stock</Link><Link className="text-primary" href="/inventory?status=low">Low stock</Link><Link className="text-primary" href="/inventory?status=out">Out of stock</Link></div></div><Panel><Table rows={products.data} columns={[{ label: 'Product', render: p => <Link href={`/inventory/stock/${p.id}`} className="font-medium">{p.name}<p className="text-muted-foreground text-xs">{p.sku}</p></Link> }, { label: 'Category', render: p => p.category }, { label: 'Selling price', render: p => money(p.selling_price) }, { label: 'Available', className: 'text-right', render: p => `${quantity(p.available)} ${p.stock_unit}` }, { label: 'Reorder at', className: 'text-right', render: p => quantity(p.reorder_point) }, { label: 'Status', render: p => <Status tone={Number(p.available) === 0 ? 'danger' : Number(p.available) <= Number(p.reorder_point) ? 'warning' : 'good'}>{Number(p.available) === 0 ? 'Out of stock' : Number(p.available) <= Number(p.reorder_point) ? 'Reorder' : 'In stock'}</Status> }]} /><Pagination page={products} /></Panel></Page>;
}
