import { Page, Panel, Status } from '@/components/erp/page';
import { Pagination, Table } from '@/components/erp/table';
import { date, money, quantity, title } from '@/lib/format';
import { Location, Option, PageData, Product } from '@/types/erp';
type Balance = { id: string; location: Location; batch: { batch_no: string; expiry_date: string | null } | null; quantity_on_hand: string; average_cost?: string };
type Movement = { id: string; location: Option; batch: { batch_no: string } | null; quantity_delta: string; unit_cost?: string; movement_type: string; source_document_type: string; actor: Option; note: string | null; created_at: string };
export default function ProductStock({ product, balances, movements, showCost }: { product: Product; balances: Balance[]; movements: PageData<Movement>; showCost: boolean }) {
    return <Page title={product.name} description={`${product.sku} · ${product.category} · Stock and movement history`}><Panel title="Stock by location and batch"><Table rows={balances} columns={[{ label: 'Location', render: b => <div>{b.location.name}<p className="text-muted-foreground text-xs">{title(b.location.type)}</p></div> }, { label: 'Batch', render: b => b.batch?.batch_no ?? 'Unbatched' }, { label: 'Expiry', render: b => date(b.batch?.expiry_date) }, { label: 'On hand', render: b => <Status tone={Number(b.quantity_on_hand) === 0 ? 'warning' : 'good'}>{quantity(b.quantity_on_hand)} {product.stock_unit}</Status> }, ...(showCost ? [{ label: 'Average cost', render: (b: Balance) => money(b.average_cost) }] : [])]} /></Panel><Panel title="Inventory movements" description="Posted movements retain the source document, staff member and cost basis."><Table rows={movements.data} columns={[{ label: 'Date', render: m => date(m.created_at,true) }, { label: 'Movement', render: m => <Status tone={Number(m.quantity_delta) > 0 ? 'good' : 'neutral'}>{title(m.movement_type)}</Status> }, { label: 'Location / batch', render: m => <div>{m.location.name}<p className="text-muted-foreground text-xs">{m.batch?.batch_no ?? 'Unbatched'}</p></div> }, { label: 'Quantity', render: m => quantity(m.quantity_delta) }, ...(showCost ? [{ label: 'Cost', render: (m: Movement) => money(m.unit_cost) }] : []), { label: 'Staff / reason', render: m => <div>{m.actor.name}<p className="text-muted-foreground max-w-xs text-xs">{m.note}</p></div> }]} /><Pagination page={movements} /></Panel></Page>;
}
