import { Field } from '@/components/erp/field';
import { Submit, usePermissions } from '@/components/erp/page';
import { Customer } from '@/types/erp';
import { useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

export function CustomerForm({ customer }: { customer?: Customer }) {
    const can = usePermissions();
    const form = useForm({ name: customer?.name ?? '', phone: customer?.phone ?? '', email: customer?.email ?? '', address: customer?.address ?? '', notes: customer?.notes ?? '', credit_limit: customer?.credit_limit ?? '0', active: customer?.active ?? true });
    function submit(e: FormEvent) { e.preventDefault(); form.transform(data => { const result: Record<string,string|boolean> = { ...data }; if (!can('finance.manage')) delete result.credit_limit; return result; }); if (customer) form.put(`/customers/${customer.id}`); else form.post('/customers'); }
    return <form onSubmit={submit} className="space-y-4 p-5"><fieldset disabled={form.processing} className="grid gap-4 sm:grid-cols-2"><Field label="Customer name *" error={form.errors.name}><input className="erp-input" required value={form.data.name} onChange={e => form.setData('name',e.target.value)} /></Field><Field label="Phone" error={form.errors.phone}><input className="erp-input" type="tel" value={form.data.phone} onChange={e => form.setData('phone',e.target.value)} /></Field><Field label="Email" error={form.errors.email}><input className="erp-input" type="email" value={form.data.email} onChange={e => form.setData('email',e.target.value)} /></Field>{can('finance.manage') && <Field label="Credit limit (BDT)" error={form.errors.credit_limit} hint="Zero requires full payment at checkout."><input className="erp-input" type="number" min="0" step=".01" value={form.data.credit_limit} onChange={e => form.setData('credit_limit',e.target.value)} /></Field>}<Field label="Address" error={form.errors.address}><textarea className="erp-input" value={form.data.address} onChange={e => form.setData('address',e.target.value)} /></Field><Field label="Notes" error={form.errors.notes}><textarea className="erp-input" value={form.data.notes} onChange={e => form.setData('notes',e.target.value)} /></Field>{customer && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.active} onChange={e => form.setData('active',e.target.checked)} />Active customer</label>}</fieldset><Submit busy={form.processing}>{customer ? 'Save customer' : 'Create customer'}</Submit>{form.recentlySuccessful && <p role="status" className="text-sm text-emerald-700">Customer saved.</p>}</form>;
}
